version: "3.9"
services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/prod/Dockerfile
    ports:
      - "8099:80"
    networks:
      - internal
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    networks:
      - internal
networks:
  internal:
    driver: bridge
