version: "3.9"
services:
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8098:80"
    networks:
      - internal
    volumes:
      - ../app/public/:/var/www/html
      # - /logs/nginx:/var/log/nginx/
    depends_on:
      - php
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ../app/:/var/www/html
      - vendor:/var/www/html/vendor
      # - /logs/php.log:/var/log/fpm-php.www.log
volumes:
  vendor:
    driver: local
networks:
  internal:
    driver: bridge
